/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SystemResourceUsage struct {
	BandwidthIn ResourceUsage `json:"bandwidthIn,omitempty"`
	BandwidthOut ResourceUsage `json:"bandwidthOut,omitempty"`
	Cpu ResourceUsage `json:"cpu,omitempty"`
	Memory ResourceUsage `json:"memory,omitempty"`
	DirectMemory ResourceUsage `json:"directMemory,omitempty"`
}
