/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type RetentionPolicies struct {
	RetentionTimeInMinutes int32 `json:"retentionTimeInMinutes,omitempty"`
	RetentionSizeInMB int64 `json:"retentionSizeInMB,omitempty"`
}
