/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type MessageIdImpl struct {
	LedgerId int64 `json:"ledgerId,omitempty"`
	EntryId int64 `json:"entryId,omitempty"`
	PartitionIndex int32 `json:"partitionIndex,omitempty"`
}
