/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// The data of namespace isolation configuration
type NamespaceIsolationData struct {
	// The list of namespaces to apply this namespace isolation data
	Namespaces []string `json:"namespaces,omitempty"`
	// The list of secondary brokers for serving the list of namespaces in this isolation policy
	Primary []string `json:"primary,omitempty"`
	AutoFailoverPolicy AutoFailoverPolicyData `json:"auto_failover_policy,omitempty"`
}
