/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SubscriptionStats struct {
	MsgRateOut float64 `json:"msgRateOut,omitempty"`
	MsgThroughputOut float64 `json:"msgThroughputOut,omitempty"`
	MsgRateRedeliver float64 `json:"msgRateRedeliver,omitempty"`
	MsgBacklog int64 `json:"msgBacklog,omitempty"`
	BlockedSubscriptionOnUnackedMsgs bool `json:"blockedSubscriptionOnUnackedMsgs,omitempty"`
	MsgDelayed int64 `json:"msgDelayed,omitempty"`
	UnackedMessages int64 `json:"unackedMessages,omitempty"`
	Type string `json:"type,omitempty"`
	ActiveConsumerName string `json:"activeConsumerName,omitempty"`
	MsgRateExpired float64 `json:"msgRateExpired,omitempty"`
	Consumers []ConsumerStats `json:"consumers,omitempty"`
	IsReplicated bool `json:"isReplicated,omitempty"`
}
