/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AuthPolicies struct {
	NamespaceAuth map[string][]string `json:"namespace_auth,omitempty"`
	DestinationAuth map[string]map[string][]string `json:"destination_auth,omitempty"`
	SubscriptionAuthRoles map[string][]string `json:"subscription_auth_roles,omitempty"`
}
