/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// The data of a failure domain configuration in a cluster
type FailureDomain struct {
	// The collection of brokers in the same failure domain
	Brokers []string `json:"brokers,omitempty"`
}
