/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GetSchemaResponse struct {
	Version int64 `json:"version,omitempty"`
	Type string `json:"type,omitempty"`
	Timestamp int64 `json:"timestamp,omitempty"`
	Data string `json:"data,omitempty"`
	Properties map[string]string `json:"properties,omitempty"`
}
