/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PoolArenaStats struct {
	NumTinySubpages int32 `json:"numTinySubpages,omitempty"`
	NumSmallSubpages int32 `json:"numSmallSubpages,omitempty"`
	NumChunkLists int32 `json:"numChunkLists,omitempty"`
	TinySubpages []PoolSubpageStats `json:"tinySubpages,omitempty"`
	SmallSubpages []PoolSubpageStats `json:"smallSubpages,omitempty"`
	ChunkLists []PoolChunkListStats `json:"chunkLists,omitempty"`
	NumAllocations int64 `json:"numAllocations,omitempty"`
	NumTinyAllocations int64 `json:"numTinyAllocations,omitempty"`
	NumSmallAllocations int64 `json:"numSmallAllocations,omitempty"`
	NumNormalAllocations int64 `json:"numNormalAllocations,omitempty"`
	NumHugeAllocations int64 `json:"numHugeAllocations,omitempty"`
	NumDeallocations int64 `json:"numDeallocations,omitempty"`
	NumTinyDeallocations int64 `json:"numTinyDeallocations,omitempty"`
	NumSmallDeallocations int64 `json:"numSmallDeallocations,omitempty"`
	NumNormalDeallocations int64 `json:"numNormalDeallocations,omitempty"`
	NumHugeDeallocations int64 `json:"numHugeDeallocations,omitempty"`
	NumActiveAllocations int64 `json:"numActiveAllocations,omitempty"`
	NumActiveTinyAllocations int64 `json:"numActiveTinyAllocations,omitempty"`
	NumActiveSmallAllocations int64 `json:"numActiveSmallAllocations,omitempty"`
	NumActiveNormalAllocations int64 `json:"numActiveNormalAllocations,omitempty"`
	NumActiveHugeAllocations int64 `json:"numActiveHugeAllocations,omitempty"`
}
