/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PendingBookieOpsStats struct {
	DataLedgerOpenOp int64 `json:"dataLedgerOpenOp,omitempty"`
	DataLedgerCloseOp int64 `json:"dataLedgerCloseOp,omitempty"`
	DataLedgerCreateOp int64 `json:"dataLedgerCreateOp,omitempty"`
	DataLedgerDeleteOp int64 `json:"dataLedgerDeleteOp,omitempty"`
	CursorLedgerOpenOp int64 `json:"cursorLedgerOpenOp,omitempty"`
	CursorLedgerCloseOp int64 `json:"cursorLedgerCloseOp,omitempty"`
	CursorLedgerCreateOp int64 `json:"cursorLedgerCreateOp,omitempty"`
	CursorLedgerDeleteOp int64 `json:"cursorLedgerDeleteOp,omitempty"`
}
