/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type BookieInfo struct {
	Rack string `json:"rack,omitempty"`
	Hostname string `json:"hostname,omitempty"`
}
