/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)

type PersistentOfflineTopicStats struct {
	StorageSize int64 `json:"storageSize,omitempty"`
	TotalMessages int64 `json:"totalMessages,omitempty"`
	MessageBacklog int64 `json:"messageBacklog,omitempty"`
	BrokerName string `json:"brokerName,omitempty"`
	TopicName string `json:"topicName,omitempty"`
	DataLedgerDetails []LedgerDetails `json:"dataLedgerDetails,omitempty"`
	CursorDetails map[string]CursorDetails `json:"cursorDetails,omitempty"`
	StatGeneratedAt time.Time `json:"statGeneratedAt,omitempty"`
}
