/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type LedgerDetails struct {
	Entries int64 `json:"entries,omitempty"`
	Timestamp int64 `json:"timestamp,omitempty"`
	Size int64 `json:"size,omitempty"`
	LedgerId int64 `json:"ledgerId,omitempty"`
}
