/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CursorDetails struct {
	CursorBacklog int64 `json:"cursorBacklog,omitempty"`
	CursorLedgerId int64 `json:"cursorLedgerId,omitempty"`
}
