/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PartitionedTopicMetadata struct {
	Partitions int32 `json:"partitions,omitempty"`
}
