/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PersistencePolicies struct {
	BookkeeperEnsemble int32 `json:"bookkeeperEnsemble,omitempty"`
	BookkeeperWriteQuorum int32 `json:"bookkeeperWriteQuorum,omitempty"`
	BookkeeperAckQuorum int32 `json:"bookkeeperAckQuorum,omitempty"`
	ManagedLedgerMaxMarkDeleteRate float64 `json:"managedLedgerMaxMarkDeleteRate,omitempty"`
}
