/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type LoadReport struct {
	Name string `json:"name,omitempty"`
	BrokerVersionString string `json:"brokerVersionString,omitempty"`
	WebServiceUrl string `json:"webServiceUrl,omitempty"`
	WebServiceUrlTls string `json:"webServiceUrlTls,omitempty"`
	PulsarServiceUrl string `json:"pulsarServiceUrl,omitempty"`
	PulsarServiceUrlTls string `json:"pulsarServiceUrlTls,omitempty"`
	PersistentTopicsEnabled bool `json:"persistentTopicsEnabled,omitempty"`
	NonPersistentTopicsEnabled bool `json:"nonPersistentTopicsEnabled,omitempty"`
	Timestamp int64 `json:"timestamp,omitempty"`
	MsgRateIn float64 `json:"msgRateIn,omitempty"`
	MsgRateOut float64 `json:"msgRateOut,omitempty"`
	NumTopics int32 `json:"numTopics,omitempty"`
	NumConsumers int32 `json:"numConsumers,omitempty"`
	NumProducers int32 `json:"numProducers,omitempty"`
	NumBundles int32 `json:"numBundles,omitempty"`
	SystemResourceUsage SystemResourceUsage `json:"systemResourceUsage,omitempty"`
	BundleStats map[string]NamespaceBundleStats `json:"bundleStats,omitempty"`
	BundleGains []string `json:"bundleGains,omitempty"`
	BundleLosses []string `json:"bundleLosses,omitempty"`
	AllocatedCPU float64 `json:"allocatedCPU,omitempty"`
	AllocatedMemory float64 `json:"allocatedMemory,omitempty"`
	AllocatedBandwidthIn float64 `json:"allocatedBandwidthIn,omitempty"`
	AllocatedBandwidthOut float64 `json:"allocatedBandwidthOut,omitempty"`
	AllocatedMsgRateIn float64 `json:"allocatedMsgRateIn,omitempty"`
	AllocatedMsgRateOut float64 `json:"allocatedMsgRateOut,omitempty"`
	PreAllocatedCPU float64 `json:"preAllocatedCPU,omitempty"`
	PreAllocatedMemory float64 `json:"preAllocatedMemory,omitempty"`
	PreAllocatedBandwidthIn float64 `json:"preAllocatedBandwidthIn,omitempty"`
	PreAllocatedBandwidthOut float64 `json:"preAllocatedBandwidthOut,omitempty"`
	PreAllocatedMsgRateIn float64 `json:"preAllocatedMsgRateIn,omitempty"`
	PreAllocatedMsgRateOut float64 `json:"preAllocatedMsgRateOut,omitempty"`
	OverLoaded bool `json:"overLoaded,omitempty"`
	LoadReportType string `json:"loadReportType,omitempty"`
	UnderLoaded bool `json:"underLoaded,omitempty"`
	BandwidthIn ResourceUsage `json:"bandwidthIn,omitempty"`
	BandwidthOut ResourceUsage `json:"bandwidthOut,omitempty"`
	Memory ResourceUsage `json:"memory,omitempty"`
	LastUpdate int64 `json:"lastUpdate,omitempty"`
	MsgThroughputIn float64 `json:"msgThroughputIn,omitempty"`
	MsgThroughputOut float64 `json:"msgThroughputOut,omitempty"`
	Cpu ResourceUsage `json:"cpu,omitempty"`
	DirectMemory ResourceUsage `json:"directMemory,omitempty"`
}
