/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Information of adminRoles and allowedClusters for tenant
type TenantInfo struct {
	// Comma separated list of auth principal allowed to administrate the tenant.
	AdminRoles []string `json:"adminRoles,omitempty"`
	// Comma separated allowed clusters.
	AllowedClusters []string `json:"allowedClusters,omitempty"`
}
