/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ResourceUsage struct {
	Usage float64 `json:"usage,omitempty"`
	Limit float64 `json:"limit,omitempty"`
}
