/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type BundlesData struct {
	Boundaries []string `json:"boundaries,omitempty"`
	NumBundles int32 `json:"numBundles,omitempty"`
}
