/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ResourceUnit struct {
	AvailableResource ResourceDescription `json:"availableResource,omitempty"`
	ResourceId string `json:"resourceId,omitempty"`
}
